# Check code complies with google-java style guide
# and Format if not
# https://google.github.io/styleguide/javaguide.html
# 
# Workflow is triggered by:
# 1) push to main
# 2) PR created
#
# https://github.com/marketplace/actions/google-java-format


name: Code-Style

on:
    push:
        branches:
            - main
    pull_request:
        branches: '*'

jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: axel-op/googlejavaformat-action@v3
              with:
                args: "--skip-sorting-imports --replace"

